spring.application.name=TradeNest
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/tradenest
spring.datasource.username=root
spring.datasource.password=Abishek@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
jwt.secret=your-very-long-secure-secret-key-for-production-12345678901234567890
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abishekh1342003@gmail.com
spring.mail.password=liffuulqdhabiibx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

Razorpay.key_id=rzp_test_S9kt8T3tBCtdmF
Razorpay.key_secret=bidwLdKnVybx30r0fmGsI45n