spring.application.name=TradeNest
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://mysql-326b92f5-abisheka1342003-2b09.l.aivencloud.com:13797/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_h69MKe8OF-RaxMPpbgb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
jwt.secret=your-very-long-secure-secret-key-for-production-12345678901234567890
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abishekh1342003@gmail.com
spring.mail.password=liffuulqdhabiibx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

Razorpay.key_id=rzp_test_S9kt8T3tBCtdmF
Razorpay.key_secret=bidwLdKnVybx30r0fmGsI45n
